### ISSUE TITLE
Bulk override does not function

### ISSUE THREAD

**Issue by lambrex** [alowaniak/music-replacer#15]
Using a directory which previously worked as a bulk override, none of the tracks are being overridden upon selection using the in-game plugin menu. Manual single track overrides are functioning correctly. Changed from Win10 Enterprise to Win11 Edu install if that helps.

**Comment by awordley** [comment]
I can confirm I am having the same issue, I initially tried uninstalling the plugin when it stopped working due to the Music Player update, and now that I have it working again the bulk overrides feature isn't working at all and I'm currently re-assigning all my tracks manually! Hope you can look into this.

**Comment by alowaniak** [comment]
Should work again once new version is accepted.
