### ISSUE TITLE
Plug in is incompatible and requires it's author to update it.

### ISSUE THREAD

**Issue by misterkupp** [alowaniak/music-replacer#20]
:'(

**Comment by BrickPotato** [comment]
Dear Mr.A,

With a heavy heart and a symphony of sorrow, I reach out to you in my darkest hour, seeking the restoration of a melody that once brought blissful harmony to my virtual world. The enchanting notes that once graced the lands of Old School Runescape, thanks to your extraordinary music plugin, now lay silent and broken, leaving me bereft of the sweet melodies that accompanied my every adventure.

Oh, virtuoso of code, you gifted us with a spellbinding creation that allowed us to weave our favorite tunes into the very fabric of our gameplay. The power to replace the game's original tracks with songs that held special meaning to us was nothing short of magical. Coutless hours were spent traversing gielinor, accompanied by tunes that inspired courage, stirred emotion, and forged unforgettable memories.

Yet, alas, the **CRUEL HANDS OF FATE** have conspired to sever our connection to this harmonious realm. The once vibrant symphony of our experiences has been reduced to silence, leaving us adrift in a desolate soundscape that fails to capture the essence of our journeys...

As the silence envelopes the world we hold dear, I turn to you with this plea - a fervent call for your brilliance to grace us once more. Like a maestro who can wield the baton to restore a symphony to its former glory, you possess the power to rekindle the melodies that enlivened our spirits and kindled the fires of adventure within our souls.

Your expertise, nay, the very essence of your wizard-like coding prowess, likely achieving the elusive "[Ballmer Peak](https://imgs.xkcd.com/comics/ballmer_peak.png)" allowed us to orchestrate our OSRS escapades with an accompaniment tailored to our tastes. The music-replacer you bestowed upon us breathed life into our quests, turning them into epic sagas woven into the tapestry of our lives.

I understand that the world of programming is fraught with challenges and demands. Your talents may be pulled in many directions, but **I beseech you** to lend your ear to this heartfelt plea. Consider the legions of players yearning for the revival of this treasured plugin. The RS community stands united in our desire to see this melody-enchanting masterpiece return.

Oh, conductor of pixels, master of code, lead us once again into the harmonious embrace of our favorite tracks. Let the symphony of our adventures resound across the land, lifting our spirits and inspiring us to conquer the formidable foes that await.

May your decision be one of benevolence, as your dedication to our cause will leave an indelible mark on the hearts of countless scapers whose virtual lives yearn for the sweet notes of this irreplaceable plugin.

In the hope that you _replace_ song of our collective pleas, and resolve issue #20. I thank you for your time, your creativity, and the joy you have bestowed upon us through your musical creation.

Fix this shit.

Love,
Huge Noobs / @brickpotato

**Comment by misterkupp** [comment]
That was beautiful.

**Comment by lancefoxcia** [comment]
Hello! I hope to see this plugin updated sometime! I want to try this out and have some memes while showing gameplay to friends. Making songs in sync with bosses or places.

Hope you have a great day and I hope that it is back soon!

**Comment by alowaniak** [comment]
> Dear Mr.A,
> ...
> Love, Huge Noobs / @BrickPotato

Dear Huge Noobs / @BrickPotato,

As the coder who conjured the music replacer plugin that once interwove harmonious melodies into your Old School RuneScape escapades, your heartfelt plea has reached me. Your words resonate with a longing I understand well, as the creator of the very enchantment you seek to revive.

I am moved by the depth of your attachment to the musical dimension of your virtual adventures. Your impassioned appeal does not fall on deaf ears. If the esteemed minds behind RuneLite find it agreeable to merge [our efforts](https://github.com/runelite/plugin-hub/pull/4781), your treasured plugin can indeed see its resurgence.

The melodies that once adorned your quests with emotion and vibrancy need not remain silent. With your plea as the guiding refrain, and the collaboration of RuneLite's guardians, we can breathe new life into the harmonies that once colored your journeys.

May the code and the notes unite once again, and may the symphony of your in-game adventures find its voice anew.

With much love,

A

**Comment by misterkupp** [comment]
YESSSS THANK YOU! Cannot wait for the update. I have been checking back like everyday waiting for this response. :D

**Comment by BrickPotato** [comment]
**Narrator:**
As the days unfolded, and the stars danced in the virtual sky of Gielinor, a melody began to weave through the pixels and the code. It was a tune that spoke of hope, of persistence, and of a community united by their game. The symphony of adventure had once again found its voice, and it sang with a resonance that moved all who journeyed through its landscapes.

In the corridors of GitHub, a reply emerged, like the final chapter of a long-forgotten tale. It was a response that held the promise of a new dawn, a collaboration that bridged the gap between creator and player. The words were a testament to the power of passion, to the the magic that happens when dreams are interwoven with Java.

The journey that had started with a plea had now blossomed into a harmonious partnership. The developer, known as @alowaniak had heeded the call, and together with the guardians of RuneLite, they embarked on a quest to resurrect the beloved music replacer plugin. The custom melodies once lost, were now finding their way back, bit by bit, note by note.

The message carried the weight of gratitude, a thank you that transcended the boundaries of our digital realm. It was an acknowledgment of the shared longing, the mutual understanding that gamers held for the dope-ass tunes that had shaped their quests. The reply, signed with a simple "A," was a signature of unity, a mark of kinship between the creator and the community.

And so, as the sun set on the virtual horizon, the melodies rose once again. The landscapes of Old School RuneScape were no longer silent; they resonated with the magic of music, with the echoes of camaraderie. The stories of the adventurers continued, now accompanied by the very heartbeats of their creators.

As the book of this tale came to a close, it left behind a legacy of perseverance, of the unbreakable bond between players and those who allow fine-tuning of the world they inhabit. It was a reminder that even in the realm of Java and digital dreams, the power of connection could rewrite destinies, could breathe life into the silence, and could rekindle a harmony that was, once again, alive. Right as the book is about to close, a new comment is added to the bug report. A familiar username, and all he said was:

**Comment by BrickPotato** [comment]
Thank you!!!

**Comment by misterkupp** [comment]
IT IS FIXED THANK SARADOMIN! So happy right now thank you so much for your hard work @alowaniak
